version: '2'
services:
  jeecg-cloud-mysql:
    build:
      context: ./doc/db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: jeecg-cloud-mysql
    image: jeecg-cloud-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
      - 3306:3306

  jeecg-cloud-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    container_name: jeecg-cloud-redis
    hostname: jeecg-cloud-redis

  jeecg-cloud-nacos:
    restart: always
    image: nacos/nacos-server
    container_name: jeecg-cloud-nacos
    hostname: jeecg-cloud-nacos
    ports:
      - 8848:8848
    environment:
      MODE: standalone

  jeecg-cloud-gateway:
    build:
      context: ./jeecg-cloud-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: jeecg-cloud-gateway
    hostname: jeecg-cloud-gateway
    image: jeecg-cloud-gateway

  jeecg-cloud-system:
    build:
      context: ./jeecg-cloud-system/jeecg-cloud-system-biz
    restart: always
    container_name: jeecg-cloud-system
    hostname: jeecg-cloud-system
    image: jeecg-cloud-system

  jeecg-cloud-monitor:
    build:
      context: ./jeecg-cloud-monitor
    restart: always
    ports:
      - 9111:9111
    container_name: jeecg-cloud-monitor
    hostname: jeecg-cloud-monitor
    image: jeecg-cloud-monitor

  jeecg-cloud-demo:
    build:
      context: ./jeecg-cloud-demo/jeecg-cloud-demo-biz
    restart: always
    container_name: jeecg-cloud-demo
    hostname: jeecg-cloud-demo
    image: jeecg-cloud-demo
